# docker-compose.yaml
version: '3.8'
services:
  postgres:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fakedata
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data